# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.gibbs_sample_mixing_matrix <- function(A, H, B, YYt, angle_range, sin_theta, cos_theta, column_reduced_mixing_matrix, null_space) {
    .Call('_SparseBayesICA_gibbs_sample_mixing_matrix', PACKAGE = 'SparseBayesICA', A, H, B, YYt, angle_range, sin_theta, cos_theta, column_reduced_mixing_matrix, null_space)
}

gibbs_sample_mixing_matrix_inplace <- function(A, H, B, YYt, angle_range, sin_theta, cos_theta, column_reduced_mixing_matrix, null_space) {
    invisible(.Call('_SparseBayesICA_gibbs_sample_mixing_matrix_inplace', PACKAGE = 'SparseBayesICA', A, H, B, YYt, angle_range, sin_theta, cos_theta, column_reduced_mixing_matrix, null_space))
}

eigen_matrix_prod_XYt <- function(X, Y) {
    .Call('_SparseBayesICA_eigen_matrix_prod_XYt', PACKAGE = 'SparseBayesICA', X, Y)
}

utility_update_matrix_across_nodes_inplace <- function(X, Xadd) {
    invisible(.Call('_SparseBayesICA_utility_update_matrix_across_nodes_inplace', PACKAGE = 'SparseBayesICA', X, Xadd))
}

matmul_inplace <- function(mat_to_update, left_side, right_side) {
    invisible(.Call('_SparseBayesICA_matmul_inplace', PACKAGE = 'SparseBayesICA', mat_to_update, left_side, right_side))
}

calculate_YiSit <- function(Y, Si, Q) {
    .Call('_SparseBayesICA_calculate_YiSit', PACKAGE = 'SparseBayesICA', Y, Si, Q)
}

calculate_YiSit_inplace <- function(YSi, QxQStore, Y, Si, Q) {
    invisible(.Call('_SparseBayesICA_calculate_YiSit_inplace', PACKAGE = 'SparseBayesICA', YSi, QxQStore, Y, Si, Q))
}

calculate_AitYi_inplace <- function(Si, VxQStore, A, Y, Q) {
    invisible(.Call('_SparseBayesICA_calculate_AitYi_inplace', PACKAGE = 'SparseBayesICA', Si, VxQStore, A, Y, Q))
}

calculate_AitYi <- function(Si, A, Y, Q) {
    invisible(.Call('_SparseBayesICA_calculate_AitYi', PACKAGE = 'SparseBayesICA', Si, A, Y, Q))
}

sample_u <- function(u, stick_breaking_weights, cluster_membership) {
    invisible(.Call('_SparseBayesICA_sample_u', PACKAGE = 'SparseBayesICA', u, stick_breaking_weights, cluster_membership))
}

likelihood_log_sum_exp1 <- function(probs, log_probs) {
    invisible(.Call('_SparseBayesICA_likelihood_log_sum_exp1', PACKAGE = 'SparseBayesICA', probs, log_probs))
}

likelihood_log_sum_exp2 <- function(probs, log_probs) {
    invisible(.Call('_SparseBayesICA_likelihood_log_sum_exp2', PACKAGE = 'SparseBayesICA', probs, log_probs))
}

sample_cluster_membership_indicators <- function(cluster_memberships, n_in_cluster, S0, u, stick_breaking_weights, mu_h, sigma_sq_h, sigma_sq_q, H) {
    invisible(.Call('_SparseBayesICA_sample_cluster_membership_indicators', PACKAGE = 'SparseBayesICA', cluster_memberships, n_in_cluster, S0, u, stick_breaking_weights, mu_h, sigma_sq_h, sigma_sq_q, H))
}

generate_cluster_mapping_vector_inplace <- function(mapping, n_in_cluster) {
    invisible(.Call('_SparseBayesICA_generate_cluster_mapping_vector_inplace', PACKAGE = 'SparseBayesICA', mapping, n_in_cluster))
}

cleanup_cluster_ordering_inplace <- function(cluster_membership, mu_h, sigma_sq_h, n_in_cluster, mapping, actual_cluster_count) {
    invisible(.Call('_SparseBayesICA_cleanup_cluster_ordering_inplace', PACKAGE = 'SparseBayesICA', cluster_membership, mu_h, sigma_sq_h, n_in_cluster, mapping, actual_cluster_count))
}

sample_spatial_maps_inplace <- function(S0, beta, posterior_mean, posterior_variance, prior_precision, draw, AtY, X, XtX, sigma_sq_q, tau_sq, lambda_sq, mu_h_div_sigma_sq_h, sigma_sq_h, cluster_membership, I) {
    invisible(.Call('_SparseBayesICA_sample_spatial_maps_inplace', PACKAGE = 'SparseBayesICA', S0, beta, posterior_mean, posterior_variance, prior_precision, draw, AtY, X, XtX, sigma_sq_q, tau_sq, lambda_sq, mu_h_div_sigma_sq_h, sigma_sq_h, cluster_membership, I))
}

update_spatial_map_posterior_tracking_inplace <- function(S0_pm, beta_pm, Beta_ngt0, lambda_sq_posterior_mean, S0, beta, lambda_sq, n_mcmc) {
    invisible(.Call('_SparseBayesICA_update_spatial_map_posterior_tracking_inplace', PACKAGE = 'SparseBayesICA', S0_pm, beta_pm, Beta_ngt0, lambda_sq_posterior_mean, S0, beta, lambda_sq, n_mcmc))
}

calculate_DPM_hyperparameter_suffstats_inplace <- function(sum_Ssq_qh, Sbar_qh, n_in_clust_qh, S0, cluster_membership) {
    invisible(.Call('_SparseBayesICA_calculate_DPM_hyperparameter_suffstats_inplace', PACKAGE = 'SparseBayesICA', sum_Ssq_qh, Sbar_qh, n_in_clust_qh, S0, cluster_membership))
}

sample_DPM_hyperparameters_inplace <- function(mu_h, sigma_sq_h, sum_Ssq_qh, Sbar_qh, DPM_hyper_sse_unscaled, n_in_cluster_qh, n_in_cluster, sigma_sq_q, prior_shape, prior_scale, maxH) {
    invisible(.Call('_SparseBayesICA_sample_DPM_hyperparameters_inplace', PACKAGE = 'SparseBayesICA', mu_h, sigma_sq_h, sum_Ssq_qh, Sbar_qh, DPM_hyper_sse_unscaled, n_in_cluster_qh, n_in_cluster, sigma_sq_q, prior_shape, prior_scale, maxH))
}

evaluate_error_inplace <- function(Ei, Si, AtY, S0, beta, X) {
    invisible(.Call('_SparseBayesICA_evaluate_error_inplace', PACKAGE = 'SparseBayesICA', Ei, Si, AtY, S0, beta, X))
}

evaluate_sse_inplace <- function(sse, Ei) {
    invisible(.Call('_SparseBayesICA_evaluate_sse_inplace', PACKAGE = 'SparseBayesICA', sse, Ei))
}

evaluate_ssY_inplace <- function(sse, AtY) {
    invisible(.Call('_SparseBayesICA_evaluate_ssY_inplace', PACKAGE = 'SparseBayesICA', sse, AtY))
}

evaluate_reg_scale_inplace <- function(reg_scale, S0, beta, mu_h, sigma_sq_h, tau_sq, cluster_membership, lambda_sq) {
    invisible(.Call('_SparseBayesICA_evaluate_reg_scale_inplace', PACKAGE = 'SparseBayesICA', reg_scale, S0, beta, mu_h, sigma_sq_h, tau_sq, cluster_membership, lambda_sq))
}

sample_local_shrinkage_parameters_inplace <- function(lambda_sq, nu, cauchy_mixing, cauchy_mixing_prior, beta, tau_sq, sigma_sq_q) {
    invisible(.Call('_SparseBayesICA_sample_local_shrinkage_parameters_inplace', PACKAGE = 'SparseBayesICA', lambda_sq, nu, cauchy_mixing, cauchy_mixing_prior, beta, tau_sq, sigma_sq_q))
}

calculate_tausum_inplace <- function(tau_sum, beta, lambda_sq, sigma_sq_q) {
    invisible(.Call('_SparseBayesICA_calculate_tausum_inplace', PACKAGE = 'SparseBayesICA', tau_sum, beta, lambda_sq, sigma_sq_q))
}

update_vector_in_place <- function(variable, new_level) {
    invisible(.Call('_SparseBayesICA_update_vector_in_place', PACKAGE = 'SparseBayesICA', variable, new_level))
}

update_matrix_in_place <- function(variable, new_level) {
    invisible(.Call('_SparseBayesICA_update_matrix_in_place', PACKAGE = 'SparseBayesICA', variable, new_level))
}

update_matrix_in_place_rowspec <- function(variable, new_level, indices) {
    invisible(.Call('_SparseBayesICA_update_matrix_in_place_rowspec', PACKAGE = 'SparseBayesICA', variable, new_level, indices))
}

